import AppKit
import ImageIO
import UniformTypeIdentifiers

@MainActor
enum ClipboardSupport {
    static let supportedTypes: [NSPasteboard.PasteboardType] = [.string, .html, .rtf, .png, .tiff, .fileURL, .URL]
    static let privateTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
    static let maximumBytes = 8 * 1024 * 1024

    static func capture(_ pasteboard: NSPasteboard, source: NSRunningApplication?) throws -> Clip? {
        let types = pasteboard.types ?? []
        if types.contains(where: { privateTypes.contains($0.rawValue) }) { return nil }
        var bytes = 0
        var representations: [[Clip.Format]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var formats: [Clip.Format] = []
            for type in supportedTypes where item.types.contains(type) {
                // Avoid counting the same image twice toward the size limit.
                if type == .tiff && item.types.contains(.png) { continue }
                guard let data = item.data(forType: type) else { continue }
                bytes += data.count
                guard bytes <= maximumBytes else { throw failure("This copy exceeds the 8 MB history limit and was not saved.") }
                formats.append(Clip.Format(type: type.rawValue, data: data.base64EncodedString()))
            }
            if !formats.isEmpty { representations.append(formats) }
        }
        guard !representations.isEmpty else { return nil }
        var clip = Clip(id: UUID().uuidString, kind: .text, content: "",
                        sourceAppId: source?.bundleIdentifier, sourceAppName: source?.localizedName,
                        representations: representations, createdAt: Double(Int(Date().timeIntervalSince1970 * 1000)))
        let files = (pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
        if !files.isEmpty {
            clip.kind = .file
            clip.content = files.map(\.path).joined(separator: "\n")
            clip.title = files.count == 1 ? files[0].lastPathComponent : "\(files.count) files"
        } else if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff), let source = CGImageSourceCreateWithData(data as CFData, nil) {
            let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any]
            let width = properties?[kCGImagePropertyPixelWidth] as? Int ?? 0
            let height = properties?[kCGImagePropertyPixelHeight] as? Int ?? 0
            guard width > 0, height > 0, width <= 16000, height <= 16000, width * height <= 40_000_000 else { throw failure("This image exceeds the 40 megapixel history limit and was not saved.") }
            clip.kind = .image; clip.width = width; clip.height = height
            clip.content = "Image · \(width) × \(height)"; clip.title = clip.content
            let options: [CFString: Any] = [kCGImageSourceCreateThumbnailFromImageAlways: true, kCGImageSourceThumbnailMaxPixelSize: 128, kCGImageSourceCreateThumbnailWithTransform: true, kCGImageSourceShouldCacheImmediately: false]
            if let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary),
               let preview = NSBitmapImageRep(cgImage: thumbnail).representation(using: .png, properties: [:]) {
                clip.thumbnail = "data:image/png;base64," + preview.base64EncodedString()
            }
        } else if let text = pasteboard.string(forType: .string) ?? pasteboard.string(forType: .URL), !text.isEmpty {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            let url = URL(string: trimmed)
            let isURL = ["http", "https"].contains(url?.scheme?.lowercased() ?? "") && url?.host != nil && !trimmed.contains(where: { $0.isWhitespace })
            clip.kind = isURL ? .url : .text
            clip.content = text
        } else if let data = pasteboard.data(forType: .rtf), let text = NSAttributedString(rtf: data, documentAttributes: nil)?.string {
            clip.content = text
        } else { return nil }
        if clip.content.trimmingCharacters(in: .whitespacesAndNewlines).range(of: #"(?i)(password|passwd|secret|token|api[_ -]?key)\s*[:=]\s*\S+|^eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$"#, options: .regularExpression) != nil { return nil }
        return clip
    }

    static func restore(_ clip: Clip, to pasteboard: NSPasteboard) throws {
        let kind = clip.kind
        let content = clip.content
        // Check before clearing the user's current clipboard.
        if kind == .file {
            let paths = fileURLs(clip).map(\.path)
            let originalNames = content.split(separator: "\n").map { URL(fileURLWithPath: String($0)).lastPathComponent }
            for (index, path) in paths.enumerated() {
                let name = originalNames.indices.contains(index) ? originalNames[index] : "Saved file"
                guard FileManager.default.fileExists(atPath: path) else { throw failure("The original file is no longer available: \(name)") }
            }
        }
        var restored: [NSPasteboardItem] = []
        if let items = clip.representations {
            for formats in items {
                let item = NSPasteboardItem()
                for format in formats {
                    let type = NSPasteboard.PasteboardType(format.type)
                    guard supportedTypes.contains(type), let data = Data(base64Encoded: format.data) else { continue }
                    item.setData(data, forType: type)
                }
                if !item.types.isEmpty { restored.append(item) }
            }
        }
        if kind == .image {
            let hasImage = restored.contains { item in
                [NSPasteboard.PasteboardType.png, .tiff].contains { type in
                    guard let data = item.data(forType: type) else { return false }
                    return NSImage(data: data) != nil
                }
            }
            guard hasImage else { throw failure("This image has no saved image data. Copy the original image again.") }
        }
        if restored.isEmpty {
            if kind == .file {
                for path in content.split(separator: "\n") {
                    let item = NSPasteboardItem()
                    item.setString(URL(fileURLWithPath: String(path)).absoluteString, forType: .fileURL)
                    restored.append(item)
                }
            } else {
                let item = NSPasteboardItem(); item.setString(content, forType: .string); restored.append(item)
            }
        }
        guard !restored.isEmpty else { throw failure("This clip is empty.") }
        pasteboard.clearContents()
        guard pasteboard.writeObjects(restored) else { throw failure("The clipboard could not be restored.") }
    }

    static func fileURLs(_ clip: Clip) -> [URL] {
        let urls = (clip.representations?.flatMap { $0 } ?? []).filter { $0.type == NSPasteboard.PasteboardType.fileURL.rawValue }.compactMap { format -> URL? in
            guard let data = Data(base64Encoded: format.data), let string = String(data: data, encoding: .utf8) else { return nil }
            guard let url = URL(string: string), url.isFileURL else { return nil }
            return url
        }
        return urls.isEmpty ? clip.content.split(separator: "\n").map { URL(fileURLWithPath: String($0)) } : urls
    }

    static func failure(_ message: String) -> NSError { NSError(domain: "Clipboard.Clipboard", code: 1, userInfo: [NSLocalizedDescriptionKey: message]) }
}

@MainActor
extension Clip {
    var imageFileURL: URL? {
        guard kind == .file else { return nil }
        let urls = ClipboardSupport.fileURLs(self)
        guard urls.count == 1, let url = urls.first, UTType(filenameExtension: url.pathExtension)?.conforms(to: .image) == true else { return nil }
        return url
    }
    var canPreview: Bool { kind == .image || imageFileURL != nil }
}
