// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsOverlayApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashOverlayApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsOverlayApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsOverlayApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsOverlayApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsOverlayApi(lhsKey, rhsKey) {
          if deepEqualsOverlayApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsOverlayApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashOverlayApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashOverlayApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashOverlayApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashOverlayApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashOverlayApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashOverlayApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct OverlayState: Hashable {
  var overlayPermissionGranted: Bool
  var notificationPermissionGranted: Bool
  var overlayRunning: Bool
  var bubbleEnabled: Bool
  var bubbleAccessibilityEnabled: Bool
  var moonshineModelReady: Bool
  var moonshineModelDownloading: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlayState? {
    let overlayPermissionGranted = pigeonVar_list[0] as! Bool
    let notificationPermissionGranted = pigeonVar_list[1] as! Bool
    let overlayRunning = pigeonVar_list[2] as! Bool
    let bubbleEnabled = pigeonVar_list[3] as! Bool
    let bubbleAccessibilityEnabled = pigeonVar_list[4] as! Bool
    let moonshineModelReady = pigeonVar_list[5] as! Bool
    let moonshineModelDownloading = pigeonVar_list[6] as! Bool

    return OverlayState(
      overlayPermissionGranted: overlayPermissionGranted,
      notificationPermissionGranted: notificationPermissionGranted,
      overlayRunning: overlayRunning,
      bubbleEnabled: bubbleEnabled,
      bubbleAccessibilityEnabled: bubbleAccessibilityEnabled,
      moonshineModelReady: moonshineModelReady,
      moonshineModelDownloading: moonshineModelDownloading
    )
  }
  func toList() -> [Any?] {
    return [
      overlayPermissionGranted,
      notificationPermissionGranted,
      overlayRunning,
      bubbleEnabled,
      bubbleAccessibilityEnabled,
      moonshineModelReady,
      moonshineModelDownloading,
    ]
  }
  static func == (lhs: OverlayState, rhs: OverlayState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOverlayApi(lhs.overlayPermissionGranted, rhs.overlayPermissionGranted) && deepEqualsOverlayApi(lhs.notificationPermissionGranted, rhs.notificationPermissionGranted) && deepEqualsOverlayApi(lhs.overlayRunning, rhs.overlayRunning) && deepEqualsOverlayApi(lhs.bubbleEnabled, rhs.bubbleEnabled) && deepEqualsOverlayApi(lhs.bubbleAccessibilityEnabled, rhs.bubbleAccessibilityEnabled) && deepEqualsOverlayApi(lhs.moonshineModelReady, rhs.moonshineModelReady) && deepEqualsOverlayApi(lhs.moonshineModelDownloading, rhs.moonshineModelDownloading)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OverlayState")
    deepHashOverlayApi(value: overlayPermissionGranted, hasher: &hasher)
    deepHashOverlayApi(value: notificationPermissionGranted, hasher: &hasher)
    deepHashOverlayApi(value: overlayRunning, hasher: &hasher)
    deepHashOverlayApi(value: bubbleEnabled, hasher: &hasher)
    deepHashOverlayApi(value: bubbleAccessibilityEnabled, hasher: &hasher)
    deepHashOverlayApi(value: moonshineModelReady, hasher: &hasher)
    deepHashOverlayApi(value: moonshineModelDownloading, hasher: &hasher)
  }
}

private class OverlayApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return OverlayState.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class OverlayApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OverlayState {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class OverlayApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return OverlayApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return OverlayApiPigeonCodecWriter(data: data)
  }
}

class OverlayApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = OverlayApiPigeonCodec(readerWriter: OverlayApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OverlayHostApi {
  func getOverlayState() throws -> OverlayState
  func openOverlaySettings() throws
  func openNotificationSettings() throws
  func openAccessibilitySettings() throws
  func setBubbleEnabled(enabled: Bool) throws
  func startOverlay() throws
  func stopOverlay() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OverlayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { OverlayApiPigeonCodec.shared }
  /// Sets up an instance of `OverlayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OverlayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getOverlayStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.super_overlay.OverlayHostApi.getOverlayState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOverlayStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getOverlayState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getOverlayStateChannel.setMessageHandler(nil)
    }
    let openOverlaySettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.super_overlay.OverlayHostApi.openOverlaySettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openOverlaySettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openOverlaySettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openOverlaySettingsChannel.setMessageHandler(nil)
    }
    let openNotificationSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.super_overlay.OverlayHostApi.openNotificationSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openNotificationSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openNotificationSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openNotificationSettingsChannel.setMessageHandler(nil)
    }
    let openAccessibilitySettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.super_overlay.OverlayHostApi.openAccessibilitySettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAccessibilitySettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openAccessibilitySettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openAccessibilitySettingsChannel.setMessageHandler(nil)
    }
    let setBubbleEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.super_overlay.OverlayHostApi.setBubbleEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBubbleEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setBubbleEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBubbleEnabledChannel.setMessageHandler(nil)
    }
    let startOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.super_overlay.OverlayHostApi.startOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startOverlayChannel.setMessageHandler { _, reply in
        do {
          try api.startOverlay()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startOverlayChannel.setMessageHandler(nil)
    }
    let stopOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.super_overlay.OverlayHostApi.stopOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopOverlayChannel.setMessageHandler { _, reply in
        do {
          try api.stopOverlay()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopOverlayChannel.setMessageHandler(nil)
    }
  }
}
