import { escapeHTML, icon } from "../view.js";

export function renderComposer(state) {
  const canStop = state.selectedSessionId !== "home" && state.isRunning && !state.input.trim() && !state.voiceNote;
  const hasContent = state.input.trim() || state.voiceNote;
  const disabled = !state.isConnected || state.isUploadingVoice;
  return `<footer class="composer-area">${state.voiceNote ? `<div class="voice-note"><span>${icon("mic", 14)}</span><span class="voice-name">${escapeHTML(state.voiceNote.name)}</span><button aria-label="Remove voice note" data-action="remove-voice">${icon("close", 14)}</button></div>` : state.isRecording ? '<div class="recording-note">Recording… Tap the microphone to finish</div>' : ""}<div class="composer"><button class="composer-icon" data-action="pick-voice" aria-label="Attach voice note" title="Attach voice note" ${disabled || (state.isRunning && state.selectedSessionId !== "home") ? "disabled" : ""}>${icon("plus", 22)}</button><textarea data-focus="composer" rows="1" placeholder="Message" aria-label="Message" ${disabled ? "disabled" : ""}>${escapeHTML(state.input)}</textarea>${hasContent || canStop ? `<button class="send-button ${canStop ? "stop-button" : ""}" data-action="${canStop ? "stop" : "send"}" aria-label="${canStop ? "Stop" : "Send"}" title="${canStop ? "Stop" : state.isRunning && state.selectedSessionId !== "home" ? "Queue follow-up" : "Send"}" ${disabled ? "disabled" : ""}>${icon(canStop ? "stop" : "send", 18)}</button>` : `<button class="composer-icon mic-button ${state.isRecording ? "recording" : ""}" data-action="toggle-recording" aria-label="${state.isRecording ? "Finish voice note" : "Record voice note"}" title="${state.isRecording ? "Finish voice note" : "Record voice note"}" ${!state.isConnected ? "disabled" : ""}>${icon(state.isRecording ? "stop" : "mic", 20)}</button>`}</div><input id="voice-file" type="file" accept="audio/m4a,audio/mp4,audio/mpeg,audio/wav,audio/ogg,audio/webm,.m4a,.mp3,.wav,.ogg,.webm" hidden><div class="composer-caption">Agent can make mistakes. Review important actions.</div></footer>`;
}

