package main

const openCodePlugin = `// Trace CLI plugin for OpenCode.
// Auto-generated by trace enable.
// Hooks call: trace hooks opencode session-start, trace hooks opencode turn-start, trace hooks opencode turn-end, trace hooks opencode session-end.
import type { Plugin } from "@opencode-ai/plugin"

export const TracePlugin: Plugin = async ({ directory }) => {
  const TRACE_CMD = "__TRACE_CMD__"
  const seenUserMessages = new Set<string>()
  let currentSessionID: string | null = null
  let currentModel: string | null = null
  const messageStore = new Map<string, any>()

  function hookCmd(name: string): string[] {
    return ["sh", "-c", TRACE_CMD + " hooks opencode " + name]
  }

  async function callHook(name: string, payload: Record<string, unknown>) {
    try {
      const proc = Bun.spawn(hookCmd(name), {
        cwd: directory,
        stdin: new Blob([JSON.stringify(payload) + "\n"]),
        stdout: "ignore",
        stderr: "ignore",
      })
      await proc.exited
    } catch {}
  }

  function callHookSync(name: string, payload: Record<string, unknown>) {
    try {
      Bun.spawnSync(hookCmd(name), {
        cwd: directory,
        stdin: new TextEncoder().encode(JSON.stringify(payload) + "\n"),
        stdout: "ignore",
        stderr: "ignore",
      })
    } catch {}
  }

  return {
    event: async ({ event }) => {
      try {
        switch (event.type) {
          case "session.created": {
            const session = (event as any).properties?.info
            if (!session?.id) break
            currentSessionID = session.id
            seenUserMessages.clear()
            messageStore.clear()
            await callHook("session-start", { session_id: session.id })
            break
          }
          case "message.updated": {
            const msg = (event as any).properties?.info
            if (!msg) break
            messageStore.set(msg.id, msg)
            if (msg.role === "assistant" && msg.modelID) currentModel = msg.modelID
            break
          }
          case "message.part.updated": {
            const part = (event as any).properties?.part
            const msg = part?.messageID ? messageStore.get(part.messageID) : null
            if (msg?.role === "user" && part.type === "text" && !seenUserMessages.has(msg.id)) {
              seenUserMessages.add(msg.id)
              const sessionID = msg.sessionID ?? currentSessionID
              if (sessionID) await callHook("turn-start", { session_id: sessionID, prompt: part.text ?? "", model: currentModel ?? "" })
            }
            break
          }
          case "session.status": {
            const props = (event as any).properties
            if (props?.status?.type !== "idle") break
            const sessionID = props?.sessionID ?? currentSessionID
            if (sessionID) callHookSync("turn-end", { session_id: sessionID, model: currentModel ?? "" })
            break
          }
          case "session.deleted":
          case "server.instance.disposed": {
            if (!currentSessionID) break
            const sessionID = currentSessionID
            currentSessionID = null
            callHookSync("session-end", { session_id: sessionID })
            break
          }
        }
      } catch {}
    },
  }
}
`
