import AppKit
import ImageIO
import UniformTypeIdentifiers

@MainActor
enum ClipboardSupport {
    static let supportedTypes: [NSPasteboard.PasteboardType] = [.string, .html, .rtf, .png, .tiff, .fileURL, .URL]
    static let privateTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
    static let maximumBytes = 8 * 1024 * 1024

    struct Snapshot: Sendable {
        struct Format: Sendable { let type: String; let data: Data }
        let clip: Clip
        let representations: [[Format]]
        let files: [URL]
        let image: Data?
        let text: String?
        let richText: String?
    }

    static func snapshot(_ pasteboard: NSPasteboard, source: NSRunningApplication?) throws -> Snapshot? {
        let types = pasteboard.types ?? []
        if types.contains(where: { privateTypes.contains($0.rawValue) }) { return nil }
        var bytes = 0
        var representations: [[Snapshot.Format]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var formats: [Snapshot.Format] = []
            for type in supportedTypes where item.types.contains(type) {
                // Avoid counting the same image twice toward the size limit.
                if type == .tiff && item.types.contains(.png) { continue }
                guard let data = item.data(forType: type) else { continue }
                bytes += data.count
                guard bytes <= maximumBytes else { throw failure("This copy exceeds the 8 MB history limit and was not saved.") }
                formats.append(Snapshot.Format(type: type.rawValue, data: data))
            }
            if !formats.isEmpty { representations.append(formats) }
        }
        guard !representations.isEmpty else { return nil }
        let clip = Clip(id: UUID().uuidString, kind: .text, content: "",
                        sourceAppId: source?.bundleIdentifier, sourceAppName: source?.localizedName,
                        createdAt: Double(Int(Date().timeIntervalSince1970 * 1000)))
        let files = (pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
        let image = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
        let text = pasteboard.string(forType: .string) ?? pasteboard.string(forType: .URL)
        let richText = text?.isEmpty != false && files.isEmpty ? pasteboard.data(forType: .rtf).flatMap {
            NSAttributedString(rtf: $0, documentAttributes: nil)?.string
        } : nil
        return Snapshot(clip: clip, representations: representations, files: files, image: image, text: text, richText: richText)
    }

    nonisolated static func prepare(_ snapshot: Snapshot) throws -> Clip? {
        var clip = snapshot.clip
        clip.representations = snapshot.representations.map { $0.map { Clip.Format(type: $0.type, data: $0.data.base64EncodedString()) } }
        let files = snapshot.files
        if !files.isEmpty {
            clip.kind = .file
            clip.content = files.map(\.path).joined(separator: "\n")
            clip.title = files.count == 1 ? files[0].lastPathComponent : "\(files.count) files"
        } else if let data = snapshot.image, let source = CGImageSourceCreateWithData(data as CFData, nil) {
            let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any]
            let width = properties?[kCGImagePropertyPixelWidth] as? Int ?? 0
            let height = properties?[kCGImagePropertyPixelHeight] as? Int ?? 0
            guard width > 0, height > 0, width <= 16000, height <= 16000, width * height <= 40_000_000 else { throw failure("This image exceeds the 40 megapixel history limit and was not saved.") }
            clip.kind = .image
            clip.content = "Image · \(width) × \(height)"
            let options: [CFString: Any] = [kCGImageSourceCreateThumbnailFromImageAlways: true, kCGImageSourceThumbnailMaxPixelSize: 128, kCGImageSourceCreateThumbnailWithTransform: true, kCGImageSourceShouldCacheImmediately: false]
            let preview = NSMutableData()
            if let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary),
               let destination = CGImageDestinationCreateWithData(preview, UTType.png.identifier as CFString, 1, nil) {
                CGImageDestinationAddImage(destination, thumbnail, nil)
                if CGImageDestinationFinalize(destination) {
                    clip.thumbnail = "data:image/png;base64," + (preview as Data).base64EncodedString()
                }
            }
        } else if let text = snapshot.text, !text.isEmpty {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            let url = URL(string: trimmed)
            let isURL = ["http", "https"].contains(url?.scheme?.lowercased() ?? "") && url?.host != nil && !trimmed.contains(where: { $0.isWhitespace })
            clip.kind = isURL ? .url : .text
            clip.content = text
        } else if let text = snapshot.richText {
            clip.content = text
        } else { return nil }
        if clip.content.trimmingCharacters(in: .whitespacesAndNewlines).range(of: #"(?i)(password|passwd|secret|token|api[_ -]?key)\s*[:=]\s*\S+|^eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$"#, options: .regularExpression) != nil { return nil }
        return clip
    }

    static func restore(_ clip: Clip, to pasteboard: NSPasteboard) throws {
        let kind = clip.kind
        let content = clip.content
        // Check before clearing the user's current clipboard.
        if kind == .file {
            for url in fileURLs(clip) {
                guard FileManager.default.fileExists(atPath: url.path) else { throw failure("The original file is no longer available: \(url.lastPathComponent)") }
            }
        }
        var restored: [NSPasteboardItem] = []
        if let items = clip.representations {
            for formats in items {
                let item = NSPasteboardItem()
                for format in formats {
                    let type = NSPasteboard.PasteboardType(format.type)
                    guard supportedTypes.contains(type), let data = Data(base64Encoded: format.data) else { continue }
                    item.setData(data, forType: type)
                }
                if !item.types.isEmpty { restored.append(item) }
            }
        }
        if kind == .image {
            let hasImage = restored.contains { item in
                [NSPasteboard.PasteboardType.png, .tiff].contains { type in
                    guard let data = item.data(forType: type) else { return false }
                    return NSImage(data: data) != nil
                }
            }
            guard hasImage else { throw failure("This image has no saved image data. Copy the original image again.") }
        }
        if restored.isEmpty {
            if kind == .file {
                for path in content.split(separator: "\n") {
                    let item = NSPasteboardItem()
                    item.setString(URL(fileURLWithPath: String(path)).absoluteString, forType: .fileURL)
                    restored.append(item)
                }
            } else {
                let item = NSPasteboardItem(); item.setString(content, forType: .string); restored.append(item)
            }
        }
        guard !restored.isEmpty else { throw failure("This clip is empty.") }
        pasteboard.clearContents()
        guard pasteboard.writeObjects(restored) else { throw failure("The clipboard could not be restored.") }
    }

    static func fileURLs(_ clip: Clip) -> [URL] {
        let urls = (clip.representations?.flatMap { $0 } ?? []).filter { $0.type == NSPasteboard.PasteboardType.fileURL.rawValue }.compactMap { format -> URL? in
            guard let data = Data(base64Encoded: format.data), let string = String(data: data, encoding: .utf8) else { return nil }
            guard let url = URL(string: string), url.isFileURL else { return nil }
            return url
        }
        return urls.isEmpty ? clip.content.split(separator: "\n").map { URL(fileURLWithPath: String($0)) } : urls
    }

    nonisolated static func failure(_ message: String) -> NSError { NSError(domain: "Clipboard.Clipboard", code: 1, userInfo: [NSLocalizedDescriptionKey: message]) }
}

@MainActor
extension Clip {
    var webURL: URL? {
        let text = content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard kind == .url, let url = URL(string: text),
              ["http", "https"].contains(url.scheme?.lowercased() ?? ""), url.host != nil,
              !text.contains(where: { $0.isWhitespace }) else { return nil }
        return url
    }

    var imageFileURL: URL? {
        guard kind == .file else { return nil }
        let urls = ClipboardSupport.fileURLs(self)
        guard urls.count == 1, let url = urls.first, UTType(filenameExtension: url.pathExtension)?.conforms(to: .image) == true else { return nil }
        return url
    }
    var canPreview: Bool { kind == .image || imageFileURL != nil }
    var spaceHint: String? { webURL != nil ? "Space to Open" : (canPreview ? "Space to Preview" : nil) }
}
