// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.super_overlay.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object OverlayApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class OverlayState (
  val overlayPermissionGranted: Boolean,
  val notificationPermissionGranted: Boolean,
  val overlayRunning: Boolean,
  val bubbleEnabled: Boolean,
  val bubbleAccessibilityEnabled: Boolean,
  val moonshineModelReady: Boolean,
  val moonshineModelDownloading: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OverlayState {
      val overlayPermissionGranted = pigeonVar_list[0] as Boolean
      val notificationPermissionGranted = pigeonVar_list[1] as Boolean
      val overlayRunning = pigeonVar_list[2] as Boolean
      val bubbleEnabled = pigeonVar_list[3] as Boolean
      val bubbleAccessibilityEnabled = pigeonVar_list[4] as Boolean
      val moonshineModelReady = pigeonVar_list[5] as Boolean
      val moonshineModelDownloading = pigeonVar_list[6] as Boolean
      return OverlayState(overlayPermissionGranted, notificationPermissionGranted, overlayRunning, bubbleEnabled, bubbleAccessibilityEnabled, moonshineModelReady, moonshineModelDownloading)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      overlayPermissionGranted,
      notificationPermissionGranted,
      overlayRunning,
      bubbleEnabled,
      bubbleAccessibilityEnabled,
      moonshineModelReady,
      moonshineModelDownloading,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OverlayState
    return OverlayApiPigeonUtils.deepEquals(this.overlayPermissionGranted, other.overlayPermissionGranted) && OverlayApiPigeonUtils.deepEquals(this.notificationPermissionGranted, other.notificationPermissionGranted) && OverlayApiPigeonUtils.deepEquals(this.overlayRunning, other.overlayRunning) && OverlayApiPigeonUtils.deepEquals(this.bubbleEnabled, other.bubbleEnabled) && OverlayApiPigeonUtils.deepEquals(this.bubbleAccessibilityEnabled, other.bubbleAccessibilityEnabled) && OverlayApiPigeonUtils.deepEquals(this.moonshineModelReady, other.moonshineModelReady) && OverlayApiPigeonUtils.deepEquals(this.moonshineModelDownloading, other.moonshineModelDownloading)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OverlayApiPigeonUtils.deepHash(this.overlayPermissionGranted)
    result = 31 * result + OverlayApiPigeonUtils.deepHash(this.notificationPermissionGranted)
    result = 31 * result + OverlayApiPigeonUtils.deepHash(this.overlayRunning)
    result = 31 * result + OverlayApiPigeonUtils.deepHash(this.bubbleEnabled)
    result = 31 * result + OverlayApiPigeonUtils.deepHash(this.bubbleAccessibilityEnabled)
    result = 31 * result + OverlayApiPigeonUtils.deepHash(this.moonshineModelReady)
    result = 31 * result + OverlayApiPigeonUtils.deepHash(this.moonshineModelDownloading)
    return result
  }
}
private open class OverlayApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OverlayState.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OverlayState -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OverlayHostApi {
  fun getOverlayState(): OverlayState
  fun openOverlaySettings()
  fun openNotificationSettings()
  fun openAccessibilitySettings()
  fun setBubbleEnabled(enabled: Boolean)
  fun startOverlay()
  fun stopOverlay()

  companion object {
    /** The codec used by OverlayHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      OverlayApiPigeonCodec()
    }
    /** Sets up an instance of `OverlayHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OverlayHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.super_overlay.OverlayHostApi.getOverlayState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getOverlayState())
            } catch (exception: Throwable) {
              OverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.super_overlay.OverlayHostApi.openOverlaySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openOverlaySettings()
              listOf(null)
            } catch (exception: Throwable) {
              OverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.super_overlay.OverlayHostApi.openNotificationSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openNotificationSettings()
              listOf(null)
            } catch (exception: Throwable) {
              OverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.super_overlay.OverlayHostApi.openAccessibilitySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAccessibilitySettings()
              listOf(null)
            } catch (exception: Throwable) {
              OverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.super_overlay.OverlayHostApi.setBubbleEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setBubbleEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              OverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.super_overlay.OverlayHostApi.startOverlay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startOverlay()
              listOf(null)
            } catch (exception: Throwable) {
              OverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.super_overlay.OverlayHostApi.stopOverlay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopOverlay()
              listOf(null)
            } catch (exception: Throwable) {
              OverlayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
