import AppKit
import ImageIO

/// Native pasteboard representations stay inside encrypted history. Preview images are local.
@MainActor
enum ClipboardSupport {
    static let supportedTypes: [NSPasteboard.PasteboardType] = [.string, .html, .rtf, .png, .tiff, .fileURL, .URL]
    static let privateTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
    static let maximumBytes = 8 * 1024 * 1024

    static func capture(_ pasteboard: NSPasteboard, source: NSRunningApplication?, ignoreSensitive: Bool) throws -> [String: Any]? {
        let types = pasteboard.types ?? []
        if ignoreSensitive && types.contains(where: { privateTypes.contains($0.rawValue) }) { return nil }
        var bytes = 0
        var representations: [[[String: String]]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var formats: [[String: String]] = []
            for type in supportedTypes where item.types.contains(type) {
                // PNG and TIFF are interchangeable image representations. Keep one lossless
                // representation rather than charging the same screenshot twice.
                if type == .tiff && item.types.contains(.png) { continue }
                guard let data = item.data(forType: type) else { continue }
                bytes += data.count
                guard bytes <= maximumBytes else { throw failure("This copy exceeds the 8 MB history limit and was not saved.") }
                formats.append(["type": type.rawValue, "data": data.base64EncodedString()])
            }
            if !formats.isEmpty { representations.append(formats) }
        }
        guard !representations.isEmpty else { return nil }
        var clip: [String: Any] = ["id": UUID().uuidString, "createdAt": Int(Date().timeIntervalSince1970 * 1000), "pinned": false, "representations": representations]
        // Only actual file URLs are files; web URLs must never become path fragments.
        let files = (pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
        if !files.isEmpty {
            clip["kind"] = "file"
            clip["content"] = files.map(\.path).joined(separator: "\n")
            clip["title"] = files.count == 1 ? files[0].lastPathComponent : "\(files.count) files"
        } else if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff), let source = CGImageSourceCreateWithData(data as CFData, nil) {
            let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any]
            let width = properties?[kCGImagePropertyPixelWidth] as? Int ?? 0
            let height = properties?[kCGImagePropertyPixelHeight] as? Int ?? 0
            guard width > 0, height > 0, width <= 16000, height <= 16000, width * height <= 40_000_000 else { throw failure("This image exceeds the 40 megapixel history limit and was not saved.") }
            clip["kind"] = "image"; clip["width"] = width; clip["height"] = height
            clip["content"] = "Image · \(width) × \(height)"; clip["title"] = clip["content"]
            let options: [CFString: Any] = [kCGImageSourceCreateThumbnailFromImageAlways: true, kCGImageSourceThumbnailMaxPixelSize: 900, kCGImageSourceCreateThumbnailWithTransform: true, kCGImageSourceShouldCacheImmediately: false]
            if let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary),
               let preview = NSBitmapImageRep(cgImage: thumbnail).representation(using: .png, properties: [:]) {
                clip["thumbnail"] = "data:image/png;base64," + preview.base64EncodedString()
            }
        } else if let text = pasteboard.string(forType: .string) ?? pasteboard.string(forType: .URL), !text.isEmpty {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            let url = URL(string: trimmed)
            let isURL = ["http", "https"].contains(url?.scheme?.lowercased() ?? "") && url?.host != nil && !trimmed.contains(where: { $0.isWhitespace })
            clip["kind"] = isURL ? "url" : "text"
            clip["content"] = text
        } else if let data = pasteboard.data(forType: .rtf), let text = NSAttributedString(rtf: data, documentAttributes: nil)?.string {
            clip["kind"] = "text"; clip["content"] = text
        } else { return nil }
        if let text = clip["content"] as? String,
           text.trimmingCharacters(in: .whitespacesAndNewlines).range(of: #"(?i)(password|passwd|secret|token|api[_ -]?key)\s*[:=]\s*\S+|^eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$"#, options: .regularExpression) != nil { return nil }
        if let source {
            clip["sourceAppId"] = source.bundleIdentifier
            clip["sourceAppName"] = source.localizedName
        }
        return clip
    }

    static func restore(_ clip: [String: Any], to pasteboard: NSPasteboard) throws {
        let kind = clip["kind"] as? String ?? "text"
        let content = clip["content"] as? String ?? ""
        // Check before clearing the user's current clipboard.
        if kind == "file" {
            let formats = (clip["representations"] as? [[[String: String]]])?.flatMap { $0 } ?? []
            let urls = formats.filter { $0["type"] == NSPasteboard.PasteboardType.fileURL.rawValue }.compactMap { format -> URL? in
                guard let encoded = format["data"], let data = Data(base64Encoded: encoded), let string = String(data: data, encoding: .utf8) else { return nil }
                return URL(string: string)
            }
            let paths = urls.isEmpty ? content.split(separator: "\n").map(String.init) : urls.map(\.path)
            let originalNames = content.split(separator: "\n").map { URL(fileURLWithPath: String($0)).lastPathComponent }
            for (index, path) in paths.enumerated() {
                let name = originalNames.indices.contains(index) ? originalNames[index] : "Saved file"
                guard FileManager.default.fileExists(atPath: path) else { throw failure("The original file is no longer available: \(name)") }
            }
        }
        var restored: [NSPasteboardItem] = []
        if let items = clip["representations"] as? [[[String: String]]] {
            for formats in items {
                let item = NSPasteboardItem()
                for format in formats {
                    guard let rawType = format["type"], supportedTypes.contains(NSPasteboard.PasteboardType(rawType)),
                          let encoded = format["data"], let data = Data(base64Encoded: encoded) else { continue }
                    item.setData(data, forType: NSPasteboard.PasteboardType(rawType))
                }
                if !item.types.isEmpty { restored.append(item) }
            }
        }
        if restored.isEmpty {
            guard kind != "image" else { throw failure("This older image has no saved image data.") }
            if kind == "file" {
                for path in content.split(separator: "\n") {
                    let item = NSPasteboardItem()
                    item.setString(URL(fileURLWithPath: String(path)).absoluteString, forType: .fileURL)
                    restored.append(item)
                }
            } else {
                let item = NSPasteboardItem(); item.setString(content, forType: .string); restored.append(item)
            }
        }
        guard !restored.isEmpty else { throw failure("This clip is empty.") }
        pasteboard.clearContents()
        guard pasteboard.writeObjects(restored) else { throw failure("The clipboard could not be restored.") }
    }

    static func failure(_ message: String) -> NSError { NSError(domain: "Palette.Clipboard", code: 1, userInfo: [NSLocalizedDescriptionKey: message]) }
}
