name: Palette

on:
  push:
    paths:
      - "tools/palette/**"
      - ".github/workflows/palette.yml"
  pull_request:
    paths:
      - "tools/palette/**"
      - ".github/workflows/palette.yml"

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build native app
        working-directory: tools/palette
        run: ./build.sh
